### PR TITLE
Update sqlite from 3.38.5 to 3.39.0

### PR DESCRIPTION
**Pull request by AndrewVallette**
## Changes
Update version from 3.38.5 to 3.39.0.

## Package Info
Home: https://www.sqlite.org/
Source: https://sqlite.org/src/dir?ci=trunk
Changelog: https://www.sqlite.org/changes.html
Bug Tracker: https://www.sqlite.org/src/rptview?rn=1
Downloads: 4024736
Last upload: 10 days and 22 hours ago

## Verifications
License is SPDX compliant
`doc_url` is correct
`dev_url` is correct
`build`:`number` is correct
Build succeeded for all architectures

### CODE REVIEW

**Comment by ScottBailey** [comment]
A quick note on the source link, it should be `https://sqlite.org/src/dir?ci=version-3.39.0&type=tree`. No need to change it, this is just for future information.

**Review by ScottBailey — APPROVED** [review]
LGTM

**Review by skupr-anaconda — APPROVED** [review]

**Review by varlackc — APPROVED** [review]
LGTM

**Comment by skupr-anaconda** [comment]
It's time to update it to the **v3.39.2**

**Pull request merged**
